FROM mysql:5.7
EXPOSE 3306

ENV MYSQL_ROOT_PASSWORD=WIZARD
ENV MYSQL_DATABASE=cardmodule
ENV MYSQL_USER=wizard
ENV MYSQL_PASSWORD=wizard

ENV TZ=Europe/Berlin

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \ 
	echo $TZ > /etc/timezone