version: '3.0'
services:
  root:
    image: wizard-root:latest
    hostname: root
    tty: true
    ports:
      - "1233:1233"
    depends_on:
      - cardmodule
      - resulttablemodule
    #command: ["./wait-for-it.sh", "-t", "60", "cardmodule:1234"]
  cardmodule:
    image: wizard-cardmodule:latest
    hostname: cardmodule
  resulttablemodule:
    image: wizard-resulttablemodule:latest
    hostname: resulttablemodule