version: '3.0'
services:
  root:
    image: wizard-root:latest
    hostname: root
    tty: true
    ports:
      - "1233:1233"
    depends_on:
      - cardmodule
      - resulttablemodule
    #command: ["./wait-for-it.sh", "localhost:1234", "--", "localhost:54251"]
  cardmodule:
    image: wizard-cardmodule:latest
    hostname: cardmodule
    ports:
      - "1234:1234"
  resulttablemodule:
    image: wizard-resulttablemodule:latest
    hostname: resulttablemodule
    ports:
      - "54251:54251"
