version: '3.0'
services:
  root:
    image: wizard-root:latest
    ports:
      - "1233:1233"
  CardModule:
    image: wizard-cardmodule:latest
    hostname: cardmodule
    #ports:
    #  - "1234:1234"
  ResultTableModule:
    image: wizard-resulttablemodule:latest
    hostname: resulttablemodule
    #ports:
    #  - "54251:54251"
