version: '3.0'
services:
  root:
    image: wizard-root:latest
    hostname: root
    tty: true
    ports:
      - "1233:1233"
    depends_on:
      - rootdb
      - cardmodule
      - resulttablemodule
    command: ["./wait-for-it.sh", "-t", "60", "wizard-root-db:3306"]
  rootdb:
    image: wizard-root-mysql:latest
    hostname: wizard-root-db

  cardmodule:
    image: wizard-cardmodule:latest
    hostname: cardmodule
    depends_on:
      - cardmoduledb
    command: ["./wait-for-it.sh", "-t", "60", "wizard-cardmodule-db:3306"]
  cardmoduledb:
    image: wizard-cardmodule-mysql:latest
    hostname: wizard-cardmodule-db

  resulttablemodule:
    image: wizard-resulttablemodule:latest
    hostname: resulttablemodule
    depends_on:
      - resulttablemoduledb
    command: ["./wait-for-it.sh", "-t", "60", "wizard-resulttablemodule-db:3306"]
  resulttablemoduledb:
    image: wizard-resulttablemodule-mysql:latest
    hostname: wizard-resulttablemodule-db
